### ISSUE TITLE
Issue with @rutter/rutter-link@1.1.1 dependency when using esm loading

### ISSUE THREAD

**Issue by zlintz** [Rutter/react-rutter-link#14]
It looks like the `"module": "dist/index.esm.js",` is not being exported into the `/dist` of dependency `@rutter/rutter-link@1.1.1`

![image](https://github.com/Rutter/react-rutter-link/assets/13058008/774fd42f-9e8c-49b2-9a5f-f0316e962245)

```bash
  VITE v4.5.0  ready in 254 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
✘ [ERROR] Failed to resolve entry for package "@rutter/rutter-link". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at Object.resolveId (file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:65922:21
    at async file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:39976:34
    at async requestCallbacks.on-resolve (/.../ui/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/.../ui/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:39956:19)
    at handlePlugins (/.../ui/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/.../ui/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/.../ui/node_modules/esbuild/lib/main.js:786:5)
    at /.../ui/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/.../ui/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/.../ui/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///.../ui/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:46041:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/react-rutter-link/dist/index.esm.js:428:14:
      428 │       require('@rutter/rutter-link');
```

**Comment by apokto-maruf** [comment]
Any update on this?

**Comment by apokto-maruf** [comment]
I made a minimum reproduction repository [here ](https://github.com/apokto-maruf/react-rutter-issue-) for anyone taking a look
